language: python
matrix:
 include:
  - python: "3.7"
    dist: xenial
  - python: "3.8"
    dist: xenial
  - python: "3.9"
    dist: focal
  - python: "3.10"
    dist: focal
  - python: "3.11"
    dist: jammy

before_install:
 - pip install coverage
 - pip install --upgrade 'importlib-metadata > 4'
install:
 - pip install ".[test]" .
script:
 - coverage run -m unittest discover
after_success:
 - bash <(curl -s https://codecov.io/bash)
